name: PR Verification (All Terraform Modules)

on:
  workflow_call:
    inputs:
      pr_number:
        description: 'Pull Request number to comment on'
        required: true
        type: string
      target_repo_owner:
        description: 'Owner of the repository where the PR lives (e.g., chakratechgeek)'
        required: true
        type: string
      target_repo_name:
        description: 'Name of the repository where the PR lives (e.g., sstest)'
        required: true
        type: string
    secrets:
      PR_COMMENT_TOKEN:          # Fine-grained PAT with Issues & Pull requests: write on target repo
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true

jobs:
  find-all-terraform-modules:
    name: Find All Terraform Modules
    runs-on: ubuntu-latest
    outputs:
      tf_dirs: ${{ steps.set-tf-dirs.outputs.tf_dirs }}
    steps:
      - uses: actions/checkout@v4

      - name: Ensure jq is available
        run: |
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update && sudo apt-get install -y jq
          fi

      - name: Discover all folders containing .tf
        id: set-tf-dirs
        shell: bash
        run: |
          mapfile -t tf_dirs < <(
            find . -type f -name '*.tf' -not -path './.git/*' \
              | xargs -n1 dirname \
              | sort -u
          )
          if [ ${#tf_dirs[@]} -eq 0 ]; then
            echo "tf_dirs=[]" >> "$GITHUB_OUTPUT"
          else
            tf_dirs_json=$(jq -c -n '$ARGS.positional' --args "${tf_dirs[@]}")
            echo "tf_dirs=$tf_dirs_json" >> "$GITHUB_OUTPUT"
          fi

  terraform-plan:
    name: Terraform Plan
    needs: find-all-terraform-modules
    if: needs.find-all-terraform-modules.outputs.tf_dirs != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJson(needs.find-all-terraform-modules.outputs.tf_dirs) }}
    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION:    ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init
        working-directory: ${{ matrix.dir }}

      - name: Terraform validate
        run: terraform validate
        working-directory: ${{ matrix.dir }}

      - name: Terraform plan
        run: terraform plan -out=plan.out
        working-directory: ${{ matrix.dir }}

      - name: Generate Terraform plan JSON
        run: terraform show -json plan.out > plan.json
        working-directory: ${{ matrix.dir }}

      - name: Comment PR with plan result
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.PR_COMMENT_TOKEN }}
          repository: ${{ inputs.target_repo_owner }}/${{ inputs.target_repo_name }}
          issue-number: ${{ inputs.pr_number }}
          body: |
            ## Terraform Plan for `${{ matrix.dir }}`
            ✅ Plan completed successfully.

            - **Directory**: `${{ matrix.dir }}`
            - **Status**: Plan generated
            - **Timestamp**: ${{ github.run_id }} / ${{ github.run_number }}

  pr-verification:
    name: PR Verification Summary
    runs-on: ubuntu-latest
    needs: [find-all-terraform-modules, terraform-plan]
    if: always()
    steps:
      - name: Summarize
        run: |
          echo "✅ PR Verification completed"
          echo "Terraform modules: ${{ needs.find-all-terraform-modules.outputs.tf_dirs }}"
          echo "Plan job result: ${{ needs.terraform-plan.result }}"
